### ISSUE TITLE
Update Clarity types to support string-ascii and string-utf8

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-transactions-js#110]
Two additional Clarity value types need to be added to support the change on the blockchain. This is a breaking change to the existing wire format of transactions.

Related PR:
https://github.com/blockstack/stacks-blockchain/pull/1779

**Comment by njordhov** [comment]
As ascii text is valid utf-8, they can be combined into a single value type.

**Comment by lgalabru** [comment]
Correct, but there is a 4x cost savings when using the ascii class.

**Comment by njordhov** [comment]
There are compression schemes like [BOCU](https://en.wikipedia.org/wiki/Binary_Ordered_Compression_for_Unicode) that can be used for efficient storage of Unicode character points. 

When a character set has been declared, as proposed in https://github.com/clarity-lang/reference/issues/3, the encoding can naively be compressed to be bound by bytes required to encode the character points in the set, avoiding having to pessimistically allocate up to 4 bytes per unicode character. 

More efficient compression schemes can also be applied. Perhaps there is an opening to devise a novel scheme tailored to the particular requirements for on chain storage including minimizing the pessimistic estimate.

**Comment by njordhov** [comment]
The wire format for unicode text should declare the expected character set in addition to the encoding.

**Comment by njordhov** [comment]
> This is a breaking change to the existing wire format of transactions.

Can you explain in more detail why this has to be a breaking change?

**Comment by yknl** [comment]
> > This is a breaking change to the existing wire format of transactions.
> 
> Why does this have to be a breaking change?

It is a breaking change in the wire format. As in it will cause unexpected behaviour in apps that try to decode the transactions due to the addition of 2 new types.

**Comment by njordhov** [comment]
> As in it will cause unexpected behaviour in apps

@yknl Why does adding the two new types have to cause unexpected behavior in apps?

**Comment by yknl** [comment]
Clarity values are serialized with a 1-byte type ID prefix:
https://github.com/blockstack/stacks-blockchain/blob/master/sip/sip-005-blocks-and-transactions.md#clarity-value-representation
