### ISSUE TITLE
Support for unsigned transactions

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-transactions-js#112]
Hardware wallets, such as Ledger devices, sign transactions while keeping the private key on the device. To support these, we need a way to create unsigned transaction, and later, pass a signature to it.

Consider the [Stacks Ledger app](https://github.com/Zondax/ledger-blockstack/), by @zondax, which accepts a serialised transaction, and returns a signature.

Eventually we'll need this for all transaction types, but starting with stx transactions, this requires modifying/extending the [`makeSTXTokenTransfer`](https://github.com/blockstack/stacks-transactions-js/blob/master/src/builders.ts#L261) function.

**Comment by yknl** [comment]
Implemented in https://github.com/blockstack/stacks-transactions-js/pull/109
