### ISSUE TITLE
Export helper function cvToHex and parseReadOnlyResponse

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-transactions-js#126]
**Is your feature request related to a problem? Please describe.**
I want to use the read-only function call of the blockstack-api-client library. It requires to provide arguments as hex encoded string. The response needs to converted to a clarity value.

I want to use the hex encoded string to make rpc calls using curl

**Describe the solution you'd like**
* Export function `cvToHex` and `parseReadOnlyResponse` by this library.
* Rename `parseReadOnlyResponse` to `hexToCv`

**Describe alternatives you've considered**
* copy paste the code from `cvToHex` - duplicate code is not good in general.
* adjust the client library so that clarity values can be passed as read-only function arguments - it is not possible to specify this specific argument and result handling in openapi (that is used to generate the client)

**Comment by yknl** [comment]
If we rename `parseReadOnlyResponse` to `hexToCv` it should also check if `0x` prefix is present. Right now it assumes the hex string is prefixed with `0x` since that's the response from the blockchain API.

**Comment by friedger** [comment]
If we  check for `0x` prefix we should also have an option for `cvToHex` to omit the prefix. 

My understanding of `hex` is that it has a prefix. Everything else is not a `hex`

We should just make sure that parsing invalid hex strings fails meaningfully.

**Comment by yknl** [comment]
meaningful failure in lieu of checking for prefix works for me 👍

**Comment by friedger** [comment]
As discussed with yknl, we should not rename the function `parseReadOnlyResponse` but also add helper functions for map entry function.

**Comment by friedger** [comment]
I missed the transactions result of the blockchain api. There we need also to decode a hex string. Defining a specific helper method for that is too much, I think. Therefore, I would add a `hexToCV` helper method.

**Comment by friedger** [comment]
@yknl PR for monorepo: https://github.com/blockstack/blockstack.js/pull/826

**Comment by friedger** [comment]
Fixed in stacks.js https://github.com/blockstack/stacks.js/pull/826
