### ISSUE TITLE
Address Generation

### ISSUE THREAD

**Issue by AnasSaeed123** [blockstack/stacks-transactions-js#129]
I am integrating blockstack in OPOLO wallet. I have problem in generating address of blockstack in c language.

Which encoding is used in blockstack?

I am using base32_encode in c with alphabets given in stacks_transaction.js

**Comment by friedger** [comment]
it uses a base 32 encoding with checksum:
https://github.com/blockstack/c32check/blob/master/src/address.ts

**Comment by AnasSaeed123** [comment]
Is there any library available in c for base 32 encoding with checksum?

**Comment by diwakergupta** [comment]
> Is there any library available in c for base 32 encoding with checksum?

Not that I know of. I'm sure the community would appreciate if someone were to build a C implementation! Note that we do have Rust code for this in stacks-blockchain; presumably you could reuse some of that to generate C-bindings. YMMV.

Either way, sounds like this can/should be closed?

**Comment by agraebe** [comment]
The [account guide](https://docs.blockstack.org/stacks-blockchain/accounts#creation) might have additional info that could help you @AnasSaeed123. I'm closing this. Please reopen if you have anything else.
