### ISSUE TITLE
Implement fee rate estimation

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-transactions-js#14]
Developers should be able to use this library to estimate transaction costs in order to set a fee rate. This should be accomplished using the fee estimate end point on a core node.

**Comment by jeffdomke** [comment]
@yknl can you please add some details, test cases, or todos here please.

**Comment by jeffdomke** [comment]
@kantai what are your plans for fees in phase 1?

**Comment by kantai** [comment]
The plan for fees in phase 1 is that transactions will need to just pay minimal fees -- essentially 1 microstack per byte of the transaction.

**Comment by friedger** [comment]
Why is this only an estimate? Isn't clarity deterministic?

**Comment by kantai** [comment]
> Why is this only an estimate? Isn't clarity deterministic?

Miners are still ultimately deciding which transactions to include in a block based on fee markets. This requires estimation of an appropriate fee for block inclusion.
