### ISSUE TITLE
Update token transfer transactions to support a contract address

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-transactions-js#24]
Update the STXTokenTransfer transaction payload to use a principal instead of a Stacks address recipient. This is because we'll want to support sending STX to either a standard principal or a contract principal. Related to: https://github.com/blockstack/stacks-blockchain/issues/1317

**Comment by zone117x** [comment]
The core node changes have been merged into master. See https://github.com/blockstack/stacks-blockchain/pull/1396/files#diff-7235ed26a43dfe5e3c6349c57ef69328R627-R651
