### ISSUE TITLE
Refactor to aid deserialization

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-transactions-js#30]
**Current architecture**
- Abstract class `StacksMessage` is the parent class of all serializable stacks-related values
    - It has 3 methods:
        - `serialize(): Buffer`
            - serialize into a `Buffer`
        - `deserialize(bufferReader): void`
            - deserialize from a `BufferReader`
            - requires class’s properties to be nullable since it relies on the static `deserialize()` method below to create an instance of the class (with null properties), and then it sets the properties.
        - `static deserialize()`:
            - instantiate a new instance of the child class
            - call its deserialize method
            - return the instance
- All stacks value classes extend `StacksMessage` and implement `serialize` and `deserialize`
- There are often multiple layers of abstraction involved in representing a value
    - example: `StacksMessage` > `Principal` > `StandardPrincipal`

**Proposal**
- The current mode of abstraction encourages deserializing to generic parent classes instead of more specific, and useful, child classes.
- For example, to deserialize a `StandardPrincipal`, you call `Principal.deserialize(bufferReader)`.
    - This creates an instance of the `Principal` class, rather than an instance of the `StandardPrincipal` class.
    - This often makes debugging more difficult since you have to dig through the object to learn about what it is, rather than being able to just inspect its type.
- We should instead be deserializing to the most specific class possible. I think a slightly different style of abstraction would facilitate this.

**Proposed Changes**
- Stacks value classes shouldn’t have nullable properties
    - these classes should closely mirror the stacks value types as described in the SIPs / Rust code base
    - rather than using nullable properties to represent values that might only exist in a certain child class, move those values to the child class
    - For example:
        - We can get rid of the `StacksTransaction` class, instead implementing a class for each kind of stacks transaction. We can then create a Typescript union type called `StacksTransaction` that includes all of the transaction types.
- Remove static `deserialize` method from `StacksMessage`
    - possibly remove `StacksMessage` class altogether?

**Comment by reedrosenbluth** [comment]
https://paper.dropbox.com/doc/Proposal-stacks-transactions-js-refactor--AwsH7eAvo~SyExeLWtRSi~02AQ-d59nnRtAwvqZByFlqET5r

**Comment by jeffdomke** [comment]
Thx @reedrosenbluth read the proposal. Any reason we can't just drop that in the ticket? What kind of next step/review do you need? Maybe @zone117x and @yknl can chime in here?

**Comment by reedrosenbluth** [comment]
@jeffdomke Happy to put it in the ticket!

**Comment by reedrosenbluth** [comment]
Here's a similar refactor I just did to the Clarity Value portion of this code base: https://github.com/blockstack/stacks-transactions-js/pull/32

This is the same kind of refactor I'm proposing for the rest of the library.
