### ISSUE TITLE
Tx validation utility helpers

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-transactions-js#46]
Building the explorer, would be really handy to have utility functions to validate tx hashes and addresses.

To be clear, I mean whether a given input matches that of a valid hash format, not a look up to see whether the tx exists.

Is this the kind of functionality we think should live here?

**Comment by yknl** [comment]
For validating tx hashes, you can check that it's a valid sha512/256 hash. That's pretty much all you can do in terms of validation. For address format validation, there's the c32check lib which this lib uses internally: https://github.com/blockstack/c32check

**Comment by agraebe** [comment]
can this issue be closed or do you have another follow up @kyranjamie ?
