### ISSUE TITLE
Transaction Testing placeholder

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-transactions-js#48]
Spoke to @yknl this morning to align on testing for the Transaction library. Currently he does not want to waste QA cycles on testing the raw Transaction Library it self and thinks the time would be better utilized testing all transactions in the Explorer and Authenticator/ Transaction signing front end. 

If this changes I will update this ticket with the details.

**Comment by timstackblock** [comment]
Hey guys just following up, are there any updates on testable functionality that I can get started with this week?

**Comment by aulneau** [comment]
@timstackblock I will write up a document today outlining how to properly test the explorer :)
