### ISSUE TITLE
Wrong property postConditionMode in test 'make contract call with post condition mode allow'

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-transactions-js#49]
In the test about contract call with post condition mode the serialized string contains PostConditionMode 02 (deny), not 01 (allow)

https://github.com/blockstack/stacks-transactions-js/blob/8e8530aba67db7c770e7a6b8bc28864359ff89a6/tests/src/builder-tests.ts#L276

..a358603**02**00000000021ae6c05355e...

Is this intended? Or am I reading the bytes wrongly?

**Comment by zone117x** [comment]
The default is 0x02 (deny) and can be specified in the builder function https://github.com/blockstack/stacks-transactions-js/blob/8e8530aba67db7c770e7a6b8bc28864359ff89a6/src/builders.ts#L253

FWIU this is intentional

**Comment by friedger** [comment]
@zone117x The test specifies allow:

https://github.com/blockstack/stacks-transactions-js/blob/8e8530aba67db7c770e7a6b8bc28864359ff89a6/tests/src/builder-tests.ts#L258

**Comment by zone117x** [comment]
Oh I see, it's a typo `postConditMode`
