### ISSUE TITLE
Change fee rate to fee

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-transactions-js#55]
The fee rate in the wire format is actually a total fee for the transaction. References to "fee rate" in this library should be changed to "fee".

**Comment by hstove** [comment]
Ah! This actually makes a lot more sense. I was a bit confused as to why nodes would say a fee "rate" was too low for one TX, and not another.

So, the proper way to show a fee is to:

- Get fee rate from the node
- Multiply `rate * tx.serialize().toString('hex')`

Ya?

**Comment by yknl** [comment]
> Get fee rate from the node
Multiply rate * tx.serialize().toString('hex')

That's correct. I'll update the fee estimation PR shortly.
