### ISSUE TITLE
Add sponsored transaction generation

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-transactions-js#7]
Currently the library can only construct transactions signed and paid for by the originating key. Sponsored transactions allow a separate funder to pay for the transaction. 

This means that the library should be able to generate transactions that are signed but does not specify the fee rate. The sponsor should then be able to deserialize the transactions, set the fee rate and sign the transaction.

**Comment by jeffdomke** [comment]
@yknl can you please add some details, test cases, or todos here please.

@hstove thought you might want to chime in on how authenticator may consume this.

**Comment by hstove** [comment]
Just a test or example in the README would be enough to let me figure out how to use it

**Comment by RaldyDaldy** [comment]
> Currently the library can only construct transactions signed and paid for by the originating key. Sponsored transactions allow a separate funder to pay for the transaction.
> 
> This means that the library should be able to generate transactions that are signed but does not specify the fee rate. The sponsor should then be able to deserialize the transactions, set the fee rate and sign the transaction.

https://github.com/orgs/blockstack/projects/32#card-35364909

**Comment by RaldyDaldy** [comment]
Reply

Op vr 3 apr. 2020 23:18 schreef robbieS <notifications@github.com>:

**Comment by diwakergupta** [comment]
@jeffdomke @yknl confirming that this is slotted for SP8? Shall I consider this a non-blocker for Neon then?

**Comment by yknl** [comment]
I don't think there are any use cases for Neon that would require this so yes.
