### ISSUE TITLE
Question: builder method names

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-transactions-js#76]
I see we have these methods: 
- `makeSmartContractDeploy`
- `makeContractCall`
- `makeContractSTXPostCondition`
- `makeSTXTokenTransfer`

Questions:
- Why is `makeSmartContractDeploy` prefixed with `Smart` vs `makeContractDeploy` to be in line with `makeContractCall`?
- Why are we prefixing some things with `STX`? Would `makeTokenTransfer` make sense, and `makeContractPostCondition`?

**Comment by yknl** [comment]
> Why is makeSmartContractDeploy prefixed with Smart vs makeContractDeploy to be in line with makeContractCall?

Agree with removing "smart" from `makeSmartContractDeploy`

> Why are we prefixing some things with STX? Would makeTokenTransfer make sense, and makeContractPostCondition?

The reason that those functions are prefixed with STX is because there could be other types of token transfer transactions.

**Comment by reedrosenbluth** [comment]
I actually think the current naming is in line with is published in SIP-005 https://github.com/blockstack/stacks-blockchain/blob/sip/sip-005/sip/sip-005-blocks-and-transactions.md#type-1-instantiating-a-smart-contract

**Comment by reedrosenbluth** [comment]
Let's update the SIP to match the names Thomas suggested, and then we can make these changes in the tx-lib
