### ISSUE TITLE
`broadcastTransaction` error handling

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-transactions-js#80]
https://github.com/blockstack/stacks-transactions-js/blob/master/src/builders.ts#L126-L132

Curious as to why we are returning text either way and not handling any errors that it catches? In the explorer front-end I had to handle this in a bit of a hacky way. Would be great if we could pass along the errors, or type some ourselves here and pass those along.

**Comment by yknl** [comment]
This is a known issue and is being addressed. Tracking this in: https://github.com/blockstack/stacks-transactions-js/issues/54

**Comment by aulneau** [comment]
Ah perfect, closing in favor of that. Thank you!
