### ISSUE TITLE
Add support for calling read-only functions

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-transactions-js#89]
It would be nice to use the same library to make contract calls as well as read-only function calls.

**Comment by aulneau** [comment]
See here 😊 https://github.com/blockstack/stacks-transactions-js/pull/87

**Comment by zone117x** [comment]
Closed?

**Comment by yknl** [comment]
> Closed?

Works in transaction lib now:
https://github.com/blockstack/stacks-transactions-js#calling-read-only-contract-functions

Still being implemented in the CLI.
